language: ruby
cache: bundler
rvm:
- 2.4.1
script:
- bash ./_scripts/update.sh
branches:
  only:
  - master
env:
  secure: XsV8Lm5LwQY3QbRkHbjJFRQe4Zx9xFSQG9MZq8OYjSWVve8vrzO/M6ohQMZpEoFIGeNlX781orCeKZGBuP6ZEGGOq7rgDSRhnMhZqPgo+KFYpFKWdCPBJyAx1JXOcuS1f4TPDyOWfl+Pc2LKbqBBCyAssKGea374gn+PFZo5SwnfRhTOpgfq1VRjyOc1CScM6Pcu0rDeMsxYQQ6sVFyeAbik/3wUEJsfjyanMifMz0V3k3aXT/qxzkny/XVkD7y4K3UHlbJRSkivqWRCTHo3u/+IgNevj39S+DkgJyovwELFI2Ko9Md5GD4DTvfC3PGg37ATUMG6LsVYo+alNeDVAIQbFxENuI3DcrShFhfem+w8PdSzBqU/Uw3Ebf69kCESo9shsW68RtZIWwfoxC8ohgcklWJ6TJRGyrQ6iOHzcpnWFIF8zXVhqhUgIHGUuR8MtwVRuKpfVvwQ/nE5qVdtHl00S7b372W54P6YeELYXpw3FhzGa2xxgd/x/kPbu7BSQv4gEYZHF+TP5pRtNFT49oaS3fXSbZzZL9st67VQtm30QwV9OdPz6yI5ddZxnkF5mPOhCFcug3iuCQboZGHkrRn3wb8uMXfO+och39GKvy14Wf7Il6uxSg/iSRIUvChLlf2K/XwB40xSA4QyKgCqyAr7sfMrEu41TaX8IkDUcCQ=
