language: ruby
cache: bundler
rvm:
- 2.4.1
script:
- bash ./_scripts/update.sh
branches:
  only:
  - master
env:
  secure: DBxvvuFSRUlM2+JO41KLKbvoaackJZcKyssa5ljo7APnG4l8tdV9DffkeMO5sWWz8REM2VsBo7ZqfiJqCv6YWhmi2aFIAFQWMO6tmpzvVLZv+0LKpNKU+6avXQuGP4twfZnBuUSgp+lkwvtqmv72XNNU3r4JzM8PycLIIqyL2BRCmEJFT/rKg0rPgz0IFoEm4Kh0jqF1eEjvQuMK5x5Y4o5eQAbIwTIk9EpcdakCyGVngsKzilh/wvMgEd44Pxp+JPNOlcBtzppqEd3rWVu4YQfoXczjnHhbD3eZXp+1Oy5CfTzSV2hwqAKX2MOiLQwOgoVb1Q4xoyUiwBr2j0vhlL05Mz8DglAMtpbXGHoNKsIdwWR/D/XoAR6BI6+PlKCczpz8nNw+dAjhKM/E2UBkqf4Hga5jsUlnVFz9Ugw/Fa7oEFLCG8cDyEfok+0/xCzOiBhMQvY+WODwJucaeboOKNwp3lA34Kr9HPYyWWFf1le4LX/L9VuTGxSlJvd1N47Zoqg9BoN/2IEsdQYWMsbqKcduvdbs5pHHkv7ILxL/yjA9IKTp9pADBtppHm+Dy0jfRcp46gmq/4fKVx9L6kbffFGUMXXyJUuOV058E/lDc1G5AX54LilzZQiGQP11hxQA3CqLd4J778d1ldXdHVA94BD46dpySuwdOHPsvs13ML8=
