language: ruby
cache: bundler
rvm:
- 2.4.1
script:
- bash ./_scripts/update.sh
branches:
  only:
  - master
env:
  secure: XvMAQEAiNQNuVZNcUYV/qEzIKRsOFoge5iZt2/DbzsIc4KHNNI/qvT111T3tV26aRUm26DsnDs4IaEYV+bVWczpJtpn8YkbOQ9SqyYtaOYXK87UG/RpToRXSbhl/vZzzJsrqvb0Eg0A6QwLJV3ooy2QITbKvVC7fd3nIHpu7OnPvw6jBaV3rDRyxIpPtESX1B5ZjyZuCde7Ta7d8b66qrxkOak9lwtsZjeZCJQ/+sSUAf+ImPRtw/mFdlW+CDEryptXW66QteNlVx2gKEL4hcvWaPZCHuvpYdGIYVWIe+Xc0mhrwgnTOCfsQQL+K0e0z+cjytiED/FVUZ9wB0TBaO7vxVaxRTVTVw3vKsgoVNaQ0dk/3meSYw67ZHjW1WKERvfKK+ooB7khazIPIabcytI2VZm2oSvCZlo1qu95DD9imxP//t4iEkLP6yPQ5LxXF0DJZ5AW/gPfaeORk/6MG1JWu+NBbx56xP5KZCUlViAqdbsXA34hQMGVUJrOo8o34VgefeeV6y6AgcL9XkYLY4GWIBi29G4hZz1U36wM+xKuyhvKV8X69zNh0MXh+CzbLjKjX9toIKgUoQPtdn9GH2cXokCu2JABtM0a7P22qIs8wBtiBV9S+Xg/WK1zXHAGt4WnXLAGquCINnVchxQx5XZSr01ytzf8Sv/LwSd9DJBQ=
