language: ruby
cache: bundler
rvm:
- 2.4.1
script:
- bash ./_scripts/update.sh
branches:
  only:
  - master
env:
  secure: Anovgodr01yQKNmHg6nbFCe5ASuBeFy2s5+sE/q9CyisDrbD2jbaPaovmNL1sUXPoKBsBl0LrbP9NVevbCnFkLMSNlL7rQtrFfWeR+cevkOvdBlhZnR/ixs1eQpzeptcqPv53bUcC9Wd83PuLBUp0I4JvgXvgfhyxVpZ0K59I/W1wHH0rvjZQvJyHgLVGl4wu3JTfWfcSRyYxeP/Yhlj7Eb8QB83v8cGfm7DxBBPcXzSBp9wkiAzsmooohfVHNYhqJrxcJa8seg4eVgs56leTS2V6O8rMvW1yEjBbC24kHezNnyLwM0aOoxVsbYS20MMmSiSLRCqCJHBqihX4U9G2HJLhd+O0MiKDQJ5PtnYrFmGLHEn3qLLD6RCKXsKmGahRd7/RYiff3EN/9xksqFiBLnY1xdmVJDBpiy/kyamODEwfRknAhEvX8dTKhW4CNfwoNT+PukdtqSYJKX8cHizOQQjT10qkYhkyKl/gotOQpRVdGXUcnChbMxrm9Cwf62s446U65A259fQ3lok4Ehzi5ZbL72bJUG03uJ5tC9mO21KGyN+lgfa3NVhJVWQ2AIwllmtDJMQY70XB/tohkvQb8ObCqAjRVc1NCqRFL4FCevRA3z4BRTJEl3Qs6GeKqjiKMaoV+nmz17tAgv2S/ixD1SJPZnXCZGrfMQdD6ofF7Y=
