language: ruby
cache: bundler
rvm:
- 2.4.1
script:
- bash ./_scripts/update.sh
branches:
  only:
  - master
env:
  secure: dAVPUZg1v14Dh3UtygL1DGsNFZlO6sH30TZVlhxkkSBduehzmAnBS28c1c1ug/1d+27CjlA4AmTzOEwmhzBwWXmy1JWp947O1sHibOOkuiMF9wPfBYzugiycEkb1O7CJfpTIuyJycOMOseIRuD92gwTB5i/P5OQOj3fpJYjusmzWDvwQOI7Mz/WJHZKEFQiHTIxfyVXue+oA411AlRNXSueuCIpqFb/3vCIHHcvNnndR/DyRU+HnsItAiduMF1HH8MlDdkczFKC9FKTcut/WKew+M183AGlbquioGzjKa6xw+fxMkq95PfJ0QldMZC3y2ubD9heNs47Tnm0R/+4ZCyVbQKrOD9yDelpQ7aJzg4MgWNxUX1QJlgSZg3ee9VR7t3iddszNC6R0Rbxeb1hahEv9rWO+zBx5dgXfvsr2Ca3YS0evBsM/ExJ1ZzjQ/qo9y6EP8Chz9TDMtyOAtmdng03qBUgEizzoSXKZSkE9yzXRewG5Emq8mA+Xo8ljPAmb0xfeEsr8S1rg69peHHb3CkbLpvSht6BC6pOl0HtKQJlgr+x1Kir0XR3TEKnCFkH/eaRUk6jKrchgNKgBxmTWMUXUg8YW9EscDZdTQahWD9/rKGOBPjVOtn/yK/cIiGd3kvIGKScU2LHlEeJZZJI/XRW1uoORuYJv7oSdPVHyVZc=
