language: ruby
cache: bundler
rvm:
- 2.4.1
script:
- bash ./_scripts/update.sh
branches:
  only:
  - master
env:
  secure: hzyfyyCLm7lYyXW9w5OipQwDk9QuDuUsvh6pbs3w7u0RGAq0FcsvAX4BkHnDmDB30paNB6fdza6GDGB+cAbWZQWd8BfRLFJpuxZmNzTUPSSbhVkMAGQWv0uB+/mg6aUxuaC0kjke1FBOnjoOfsWPD8Drwqr3hk0reRraW6Pu+6xhpwkTSZgwIfd7ATGbHF36DriXg9l2C5dl3vh895yO1CgDiRgbJzrgatOaxbZcuk8snmMlRKi8AC+S90gv1/lVHEAVOHtLndCtaWOZz2f9OHo0GRJdzkHnIutuUFCC4ovhbhD/8fxE7a2VY50eKUN6COPMCoww3eDsl5/pUI8MCdmm6a5BdxZRuSk9E/8RdpKytBMWkS4Vll2AW5AiTCJTDnG28Fw0MgiHG60UZmwuPHqRI6jmT20tdk9hQn+dLFvVQ9DYe7MAf2BJLvyMMC4XYD2SZU3y59I2onidDFcDozleitJ3Xu3l9sMGdO9KcFyxI4WujP3EfDumDGg0TWmpK5hHAaTzcznrSCVPShB7wTc0x6oXFMK/WnhAb9k1AeHKh1G5zEbK4WEEKTw4Te5/9qtI92LgLwpVOltGZbgQ811bCa3+9nHOmfzEQLw+NPbuP/RzUvnm3tEC76A3KpM6gPsiQMoqKQlTrdELYzDQ7W+6VJy1R8/awJPSWQKDwS8=
