language: ruby
cache: bundler
rvm:
- 2.4.1
script:
- bash ./_scripts/update.sh
branches:
  only:
  - master
env:
  secure: D2W3HZhNcbuVuOqkVqqcxgyB0iQ15ofJBgcXn+Dn0YrDAaLvL0P5v5RbTk7qHfqaPQJsq9WWMaiDYDKqomhcJ6lMwrPfNFZVgCHejdPXSJwNmw4HlvPHOKFgN1Po/YwwHH9r7hQsw2/tzikxOxWGzi5KsjwygaN0nBZUFbG8ItqnJDUUlnKIkVKRAkjTh3QSvyqCc3UZ6lBKVLVo0NRtGXzJ6xlKCq/5+KfckFEYwP4WRr3KrHak9mGivNj33MKa8Gx7bYGRh+xvF1eoQVuk+M+PcTAmtEmyiPoleKcWvMmdFiqI87bnsnxWdkGP46VrHbHpGzC9x78ShCB91nH8CrTPVnPbKWkM/zk0PnKK6A1V/rwQkrlqMkoAywuhVy/HgtzBs/0QfehlpRSnkfWdiwnkMiKvoTmLAbLM/iJ3iPwFwbjfWsTmqnPazVYttCatqaI51fxKklRhOVHl7+GzJ0uLQDpr7i78RTSVg9mdHYcHT1KgBP1QfSGsiCI6LzyWnY2mXyS1zTxF8iCgDv0jC2AaS2IqrtfRnYoFK9Oh0W4t6qsQiybQpN4LUMiokWVGVBzwSa51hFbvUw9jqLfy4I6uTaQSTBGu4yoZqd54Fyopo8tm01RX95IjlA2GdA/2wdQy8mYX/02afInNWvUrbyCaKpQ66B6T2b1wU3X2xSk=
