language: ruby
cache: bundler
rvm:
- 2.4.1
script:
- bash ./_scripts/update.sh
branches:
  only:
  - master
env:
  secure: yxDZ94R/2feWsEAaa9MXMHQ/KUWC5C88KBKVl9C0O87UmLKqmGtF0VWEtNu3wF98jq1yP/r9Ooy5yGJdPq/N+njbNMnWWjgSKRFW0ze01+SX6XNldXo2dTnZ9kKrahMg5U8KiaDUpUPGNFaJosnHZ+okHU9BcPnfQ9VUbcGcAzg88ZqPeiw8bxhTslUdEfsi7HyqTGKKatRUiKkf6tO0fdcM5w0vhYf3MGRXQoHetgsUxPvU85IfVBvn/WX4Vgk1dRsPu/mNFFdrMwpoILdSyGzOkuwvwPifFTLH1Zv8xUYWBUgTbi8Zodx9DdypzVB7XPwxUzL4RxHH47mC8LOBgHk/EeoaC0QaOGPATbDapJdYO5fEnWErhvCUMW/Uxp00TK/zKq96DBiGyjHhLlU2Uoe0nKiuKWATXsxuIxCpZN7lJy3sEkmrvQoQJLQEJcOhF3UKjTL+aLYT10Cj5OsareIYYNgy8CXq3Lz/56sFrw/8gnebrqwzipuCAkQQ0nmjV+R/UZNk/k/TDTWUAivTS1CkUhvhS1ZFMSBr6P7FDWgzygvnjGIf+o+BlcjRXjhCepszalXEe8JQ6S2H10wK0wmfPimf0Azy4HHl3F2AtBmTfaCIfQL4VCRQHJTWveuvD/Qgd4XMlzPgrK5qjaI27ODi9+VOaGd/GnJr4S/kcQ4=
