language: ruby
cache: bundler
rvm:
- 2.4.1
script:
- bash ./_scripts/update.sh
branches:
  only:
  - master
env:
  secure: z3qU5xhCYKwIzkGnD9/+nn7I+60x93yx1Hrlo8HA0a9z/TUlQARQaAUY6bvK+vaBwZlEka6R/Q4Wxpgyxby9VuL+lusPfhxXwE2VbfDusKOoankQq1n68SDW2/j4t6zA15Vr6gEYNYXaBgmrWtvVslZMcG5GQ6MaWrjGLgHOHGZJwa3xP8j3COjGriC4ZhE0Ql5UllzcSEyIehCXuu4WFrZkBcXGV+mLW9qiJgws+5/boNaMfNgyRo1H1o+JoVCnR/xmucydR79gcxP2YUw7ybZbwQqeungRoPQB7SvYwgKcNJOg3mumxxum9fiOkJUgvt6nl94rQk6ztDEtP/H2C1Ia/20Ff10ZfPlPUBUmci/eODxxmwRiHwa+iDwG2I1qM1EKyduae3mexkv++Qxbf6srxg1zf3mqPlzr4FqgM/sUBEVGkObeg8CExPGH5iC+2syRFQn9j/ypX//9IjjOe4UT4pyS31JfVT0MUxa1djD9WpHnJA5kC+y/JqhKZTN1NZxhwqZURdMe5Znt1cugEkCh3ymUWqwzPE2ysoHbTWZeIkKmSTbvs1Q1uWWNeko8rvL0AnVJYneymQrUkQVZ4hiDYyyQh7ClDKDZXvuQMDJ0bxavGkUc+ngFq5fUePIeHZPnkmTmmbh3k6WRxnIAZZcO/LsALlHNvZg+InCb3Nc=
