language: ruby
cache: bundler
rvm:
- 2.4.1
script:
- bash ./_scripts/update.sh
branches:
  only:
  - master
env:
  secure: ZF4/pt2Pg+9ImhxE6Bjw1rO343N+JKnqZLCbfGwPMWlhXT5eSctaIWZhSt5t2L+2mYSTWllzo5MVh7kqBxHIu8yykhiEeFKIOfCuAe/HQbrtjkR0UN4eJLHRCroKm6gAi7eWqBhxkSi/tg17/NsxPkGH2BFSXebVANUiw6fmVVmBYRnARaFzgbcZW0nu141SRHmBz94aBnlKOPz4xlJjcZe0wy0dTY0XBrcAqnOAYQFqR1MfHThUTUS6sakZFYGW9NVrlKH28UaC+mr2T1r1sqNPBLwyB1Luo+83Bu6tX4+ngI8lkVAt0j/zpkHb1iGVAfolfMTe6vbIsb1FzOW5ZVslOHxbtkhz1+mmo1VPwTuUS9vO51aLQ7E7vhZLuF2xr/CE21R1Zd8TLD+g8D6t2mGAqw8xmueUEy3OBwaVIv0mdlxmvFBoDsyZgN6gasSb2PgAuD9X7/jMI+WfJ28KYGKjVtx1Xl9lRqpA81ZjpyDehSW9jhNDyOuFLjdJhoCP1RGhXkPdrrKXkRPzirxLFTSqKEL3hG0NVN55Yde5fAj94+SZxDZ65NfmfqO01Y6J3b21JsgQT4Eq4ihNt8bPYY+KrjwWakaDJe6x3jZtJPJVE+y2FTHHLT0PTTBqCy4S+yztmZkCE6rwAhJllbV2M6As03wuISNY7QqPIWH4zLk=
