language: ruby
cache: bundler
rvm:
- 2.4.1
script:
- bash ./_scripts/update.sh
branches:
  only:
  - master
env:
  secure: PPAMxvh4Sv4Pw9+gUWhHjuYcs5SHMmQvQHDIRQiflNeuwcPC8UQcdwJ76C7+6PXHQRsWdwEHfVIZCVqQ5FeIudaLOyEfY4eM/hV5MdzY+NsnWO0B4dmDTcpz/aBIma6wCcEeS0stCjOopMBEEJFzMSsq6SFrUVK05Sqkk2156YQ69Bhqe9zxWTeHliecI7E78cwq/C91sKqmmPsokzXSLyr8J6R0wGnPwXL3TA+Fca6lOq06Q+Lcu2Tr8rw2JRmkKQkzF2nM/Q3z7iqG7bv1H+6KWx9W3kMdRvs7mDsRXou3ViSm7TESAuN/pCSeYxK8x4YcbwSV4ca5Nw82FxUI9y/oFjr2Zv3VSYtJM74BmpAdJ3H1MA7MUsoA2/WhQQLgwzCr51DIa3cweJ+G2Qte31IzqMPsnlH0Fu1uWD/w7yTuT6RB0HtjX9PahIr/T7R7KH3xLHw+GQGMzB8fOMPKY4T1feVESsOUj8AC2Sjxici5XSSUJUAH3cczj/Q0VAo625dRlGrzytOZqhHxHaNJTTcBFF/A+NKmjbX2qDDikvlI4neOlx61rvpX8zqo0M6th0hzHyfIWDFVD7sD0+qpqQX0qROwmUTJrvfcpR1+0M4s7t1ZzwTYPECmNzVXQMFMw/yvw5YcfyvKH4bdcVu4tTWHQJqwy/nDPbVn2L4eP04=
