# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jimmy Manning
email: JimmyManning@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog containing my thoughts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jimmymanning.github.io" # the base hostname & protocol for your site
twitter_username: Jimmy_Manning
github_username:  JimmyManning
linkedin_username: james-manning-a8b6585
instagram_username: jimmyjmanning
# Build settings
markdown: kramdown
